version: '3.7'

services:
  loki:
    image: grafana/loki:2.7.3
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./data/wal:/tmp/wal
      - ./data/chunks:/loki/chunks
      - ./data/index:/loki/index
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

