version: '3.7'

services:
  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring-network

  fluent-bit:
    build: ./fluent-bit
    ports:
      - "2020:2020"
    networks:
      - monitoring-network

  loki:
    build: ./loki
    ports:
      - "3100:3100"
    networks:
      - monitoring-network

  otel-jaeger:
    build: ./otel-jaeger
    ports:
      - "8889:8889"    # OpenTelemetry
      - "14250:14250"  # Jaeger gRPC
      - "16686:16686"  # Jaeger UI
    networks:
      - monitoring-network

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge

