version: '3.8'

services:
  otel:
    image: umar3331/otel-collector:latest
    ports:
      - "4317:4317"
      - "55680:55680"
    networks:
      - monitoring

  jaeger:
    image: umar3331/jaeger:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - monitoring

  fluent-bit:
    image: umar3331/fluent-bit:latest
    ports:
      - "24224:24224"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - monitoring

networks:
  monitoring:
    external: true

