version: '3.8'
services:
  jaeger:
    build: .
    image: your-dockerhub-username/jaeger:latest
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Jaeger HTTP thrift
    networks:
      - monitoring
networks:
  monitoring:
    driver: bridge

