global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/rules/alert.rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          node: 'ec2-instance'
          network: 'eu-north-1'
          datacenter: 'aws'
          application: 'monitoring'
          exporter: 'node_exporter'
    #metric_relabel_configs:
    #- source_labels: [__name__]
    #   regex: 'node_cpu_seconds_total'
    #   action: drop

  - job_name: 'opentelemetry'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
