version: '3.8'
services:
  otel:
    build: .
    image: your-dockerhub-username/otel-collector:latest
    ports:
      - "4317:4317"
      - "55680:55680"
    networks:
      - monitoring
networks:
  monitoring:
    driver: bridge

