version: '3.8'

services:
  otel:
    build: .
    image: umar3331/otel-collector:latest
    ports:
      - "4317:4317"
      - "55680:55680"
    networks:
      - monitoring
    command: ["otelcol", "--config=/etc/otel/config.yaml"]  # Optional, if needed

