version: '3.7'

services:
  fluent-bit:
    image: umar3331/fluent/fluent-bit:latest
    container_name: fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/log:/var/log
    ports:
      - "2020:2020"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge


