version: '3.7'

services:
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3200:3200"
    volumes:
      - ./tempo-config.yaml:/etc/tempo/tempo-config.yaml
      - ./data:/var/tempo/traces
    command: -config.file=/etc/tempo/tempo-config.yaml
    networks:
      - monitoring

networks:
  monitoring:
    external: true

