server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

compactor:
  compaction:
    compacted_block_retention: 336h

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces

