name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Prometheus Image
      run: |
        docker build -t your-dockerhub-username/prometheus ./prometheus
        docker push your-dockerhub-username/prometheus

    - name: Build and Push Fluent Bit Image
      run: |
        docker build -t your-dockerhub-username/fluent-bit ./fluent-bit
        docker push your-dockerhub-username/fluent-bit

    - name: Build and Push Loki Image
      run: |
        docker build -t your-dockerhub-username/loki ./loki
        docker push your-dockerhub-username/loki

    - name: Build and Push OTel-Jaeger Image
      run: |
        docker build -t your-dockerhub-username/otel-jaeger ./otel-jaeger
        docker push your-dockerhub-username/otel-jaeger

    - name: Build and Push Grafana Image
      run: |
        docker build -t your-dockerhub-username/grafana ./grafana
        docker push your-dockerhub-username/grafana

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy with Docker Compose
      run: |
        docker-compose down
        docker-compose pull
        docker-compose up -d

