name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push OTEL image
      uses: docker/build-push-action@v2
      with:
        context: ./otel
        push: true
        tags: umar3331/otel-collector:latest

    - name: Build and push Jaeger image
      uses: docker/build-push-action@v2
      with:
        context: ./jaeger
        push: true
        tags: umar3331/jaeger:latest

    - name: Build and push Fluent-bit image
      uses: docker/build-push-action@v2
      with:
        context: ./fluent-bit
        push: true
        tags: umar3331/fluent-bit:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to Server via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/ubuntu/monitoring
          docker-compose pull
          docker-compose up -d
        EOF

